def start_title():
    from time import sleep
    import playsound
    playsound.playsound('Music/clip_08_power_of_preenfm-798.mp3', False)
    print ('...')
    print("                                                                                                                                                                                                    ")
    print("                                                                                                                                                                                                    ")
    print("                                                                                                                                                                                                    ")
    print("                                                                                                                                                                                                    ")
    print("                                                                                                                                                                                                    ")
    print("         cXNNNc                                                                                                                                                                                     ")
    print("         XMMWMN                                                                                                                                                                                     ")
    print("        kMMxdMMK                                                                                                                                                                                    ")
    print("       dMMK  kMMx                                                                                                                                                                                   ")
    print("      lWMNc   NMMl                                                                                                                                                                                  ")
    print("     cNMMl    cWMWc                                                                                                                                                                                 ")
    print("     KMMx      dMMX                                                                                                                                                                                 ")
    print("    xMMMWWWWWWWWMMMk                                                                                                                                                                                ")
    print("   lWMNddddddddddXMMd                                                                                                                                                                               ")
    print("  cNMMl          cWMWc                                                                                                                                                                              ")
    print("  XMMk            dMMNc                                                                                                                                                                             ")
    print("  ccc              ccc                                                                                                                                                                              ")
    print("                                                                                                                                                                                                    ")
    print("                                                                                                                                                                                                    ")
    print("                                                                                                                                                                                                    ")
    print("           cc                                                                                                                          lkkxc                                          ccc          c")
    print("       cxXWMMWl                                               xWc                                                            cld      dMMMMX                                         xMMMWXd       x")
    print("      xWMMMNXkc                       lKd                     kMl                                                          dWMMWc     cXWMNd                                         lKXNMMMNl      ")
    print("     dMMMXc         cldxxdc           xMk            cldxddc  kMl      cldxxdc      ckkkklxKKKKxc        cxkKXKkldkkkd   dkXMMMMkkx    xkkkl       lxKKXKkdc      ckkkklxKKKKxc          lWMMWc     ")
    print("     kMMMl        xXNKkxxkXNkc   cKWK xMk xWKl     xXNKkxxkXNxkMl    xXNKkxxkXNx    dMMMMMMMMMMMWk     cKMMMMMMMMMMMMX   KMMMMMMMMW   cWMMMx    ckWMMMMMMMMWKc    dMMMMMMMMMMMMk          kMMMd     ")
    print("    lWMMWc      cXWd       cKk  lWXl  xMk  cKMx  cNNd       cKWMl  cXWd       lNNc  dMMMMWkxxXMMMMd   lWMMMWKxxKWMMMMX   xKNMMMMKKk   cWMMMx   cNMMMWKkkKWMMMNc   dMMMMNkxxXMMMMd         lMMMXc    ")
    print("lkKXMMMWd       kMl             XWc   lkd    NWc XWl          XMl  kMdccccccccclWK  dMMMMd   cWMMMx   KMMMNc    cNMMMX     xMMMWc     cWMMMx   xMMMMl    cWMMMk   dMMMMd   cWMMMx          xMMMWKkxc")
    print("XMMMMMWd        XWc             NN           XMl NN           kMl  XMXXXXXXXXXXXXk  dMMMMl    WMMMx   KMMMNc    cNMMMX     xMMMWc     cWMMMx   xMMMWl    cWMMMk   dMMMMl   cWMMMx           kMMMMMMk")
    print("cdxKWMMMx       dMk         cc  xMx         dMX  xMx         lWMl  dMk              dMMMMl    WMMMx   lWMMMNkxxkNMMMMX     dMMMMKkx   cWMMMx   cNMMMWKxxKWMMMWc   dMMMMl   cWMMMx          KMMMNkxd ")
    print("    cNMMWc       dWXdc    lkWK   xNXdc   cdKWkc   xWXdc    lkNXMl   xWXdc    cxNK   dMMMMl    WMMMx    lXMMMMMMMMMMMMX     cXMMMMMW   cWMMMx    ckWMMMMMMMMWKc    dMMMMl   cWMMMx         dMMMK     ")
    print("     kMMMd         dKXXXXXXkl      dKXNNNNKxc      cdKXXXXXKxcxXc     dKXXXXXXkl    ckkkkc    xkkkl      lxKXXKkdxkkkd       lxkKKk    kkkkl      cdkKXXKkdc      ckkkkc    kkkkl         kMMMd     ")
    print("     lWMMNl                                                                                                                                                                              xWMMNc     ")
    print("      lNMMMWNXc                                                                                                                                                                      dXNWMMMXc      ")
    print("        dKNWWNl                                                                                                                                                                      dNWNXkl        ")
    print("                                                     clddddddddddc    lddddddddddddddl            lddddddddlc   clddddddddl            cdddddddddddc                                                ")
    print("                                                 cxKWMMMMMMMMMMMMMd  NMMMMMMMMMMMMMMMMWXd      dXMMMMMMMMMMMMNKNMMMMMMMMMMMWXl      lKWMMMMMMMMMMMMMWKl                                             ")
    print("                                               ckWMMMMMWNNNNNNNNNKc  xXNNNNNNNNNNNNNWMMMMK    XMMMMWNNNNNNWMMMMMMMNNNNNNNWMMMMk    xMMMMWNNNNNNNNNWMMMMx                                            ")
    print("                                              cNMMMWKl                               xMMMMl  xMMMWl        lWMMMNc        dMMMMl  cMMMMk           kMMMMc                                           ")
    print("                                              NMMMXc                                 cMMMMd  kMMMN          XMMMk         cMMMMd  lMMMMl          cKMMMWc                                           ")
    print("                                             dMMMWc                    lkXNWWWWWWWWWWWMMMMd  kMMMN          XMMMk         cMMMMd  lMMMMWWWWWWWWWWWMMMMMx                                            ")
    print("                                             xMMMW            kWMNl  cKMMMMMMMMMMMMMMMMMMMd  kMMMN          XMMMk         cMMMMd  lMMMMMMMMMMMMMMMMMNkc                                             ")
    print("                                             cWMMMk           WMMMx  XMMMNxlllllllllldMMMMd  kMMMN          XMMMk         cMMMMd  lMMMMxlllllllllllc                                                ")
    print("                                              dMMMMXd         WMMMx  WMMMx           lMMMMd  kMMMN          XMMMk         cMMMMd  lMMMMd                                                            ")
    print("                                               lNMMMMWXKkkkkkkWMMMx  kMMMMXkkkkkkkkkKWMMMN   kMMMN          XMMMk         cMMMMd   KMMMWKkkkkkkkkkkkkkkl                                            ")
    print("                                                 dXWMMMMMMMMMMMMMMx   xNMMMMMMMMMMMMMMMWkc   xMMMX          XMMMk          WMMMd    xWMMMMMMMMMMMMMMMMMMc                                           ")
    print("                                                    lxkkKKKKKKKKKx      lxkKKKKKKKKKKkd       xKkc          ckKx           lkkd       dxkKKKKKKKKKKKKKkd                                            ")
    print("                                                                                                                                                                                                    ")
    print("                                                                                                                                                                                                    ")
    print("                                                                                                                                                                                                    ")
    print("                                                                                                                                                                                                    ")
    print("                                                                                                                                                                                                    ")
    print("                                                                                                                                                                                                    ")
    print("                                                                                                                                                                                                    ")
    print("                                                                                                                                                                                                    ")
    print("                                                                                                                                                                                                    ")
    print("                                                                                                                                                                                                    ")                                        
    print("                                                                                                                                                                                                    ")
    sleep(4)
    playsound.playsound('Sounds/coolcatproductionpresents.mp3', False)
    print("                                                                                                                                                                                                    ")
    print("                                                                                                                                                                                                    ")
    print("                                                      cdkKKKKKKKKkc      cdxkKKkxc            lxkKKkxd        xKx                           lxkKKKKKKKKx   xKKKKKKKKKKKKxl    dKKKKKKKKKKKKKKKKx    ")
    print("                                                    xN????????????K    xN?????????Wkc      lKM????????MNd    d???d                       lKM???????????Mc cM??????????????Wd  W????????????????Mc   ")
    print("                                                  cN???Nkdlllllllc   lW???XkdldxKM??Mx    k???WKxlldkN???Nc  x???d                      kM??WKxllllllllc   cllllllllllldN??Mc  llllllN??Wllllllc    ")
    print("                                                 cW??Wl             cM??Wc       cX???d  x???k        lW??N  x???d                     k???k                            x???d        X??W           ")
    print("                                                 x???d              k???l          W??X  W??X          x???d x???d                     W??N                 lKWMMMMMMMMM????d        X??W           ")
    print("                                                 d???x              x???d         cM??X  N??N          x???l x???d                     N??W                K???WNNNNNNNNW???d        X??W           ")
    print("                                                  N??Mx             cW??Wd       lN??Ml  d???Xc       xM??X  d???d                     d???Nc             l???K         x???l        X??W           ")
    print("                                                   K???MXkkxxxxxkxc  cX???WKxxxkN???Wd    dM??MXkxxkKW???K   cM??Wkxxxxxxxxxd           dW???NKkkxxxxxxl  cW??MkkxxxxxkkM??Wc        X??W           ")
    print("                                                    lKW???????????K    lXM???????MNx       ckNM???????WKl     lXM????????????x            xXM???????????c  cKM???????????MXc         X??N           ")
    print("                                                       cldxxxxxxxd        cdxxxdl              ldxxxdc          clxxxxxxxxxxd                ldxxxxxxxxl      ldxxxxxxxdl             ddc           ")
    print("                                                                                                                                                                                                    ")
    print("                                                                                                                                                                                                    ")
    print("                                                                                                                                                                                                    ")
    print("       cdxkxdc                                                                                                                                                                                      ")
    print("      xkkkkkkkdc                                        clllc                                                                                                                                       ")
    print("     dkKKKKkkkkkdc                                   clxkKkdc                                                                                                                                       ")
    print("     xKKKKKKKKkkkxl                                ldkKKKkxc                                                                                                                                        ")
    print("    ckKKKXXXXKKKkkxdcc ccccccccccc              cdkKKKKKKkl dKKKKKKKkl   lkKKKKKKKl  lxKKKkl    dKKKKKKKkl    dKd      ckKc   dkKKKKKKlcKKKKKKKKKKKdlKx    cxkKKkdc   dKKKKKKKxl    cxKKKKKKKKl     ")
    print("    ckKKKXXXXXXKKkxxkxxdxddxxdddlllllllcllcccclxkKKXXXXXkd  N?NKKKKKM?X k?MKKKKKKKllN?MXKKW?Wx  N?WKKKKXW?Wd  N?X      l??l xM?WXKKKKKlckKKKN?MKKKKlk?W  cX?MXKKN?Mk  X?WKKKKXM?Nl cW?NKKKKKKKl     ")
    print("     xKXXXXXNXXKKkxkKkkkxxkkxdddddlldddddxdddxxkkKKXXXXKl   N?K     d??lN?K       cM?K     d??x N?K      x??l N?X      l??ld?Md             k?W     k?W  N?Nc    cW?K X?X      K?Mcl??kddddlc       ")
    print("     lKkKXXXXKKKKKKKKkkkkxxxkkxxxxddddxxddxxxxxxkKKKXXKl    N?NKKKKKM?X N?K       d??l      W?K N?K      cM?x X?N      l??lk?W              k?W     k?W  M?x      K?W X?X      c??l lXWWWWWM?Nc     ")
    print("    clxKKKkkKKXXKkkkxxxxxxxxxxkkxkkkxdxxkkxxxkkkkkkKKKl     N?WKKKKKkl  N?K        N?Wd   lX?Ml N?K     dN?Nc lM?Kl    l??lcW?Xd            k?W     k?W  k?Mxc  ckM?x X?X      c??l        cM?k     ")
    print("   cldxkKkkKXKkkkxkxxxxxxxxxkxdkKkkKkdxxkKkkkkkkxxxxxd      N?k         X?K         xN?MMM?WKc  X??MMMM??Nx    cKW??MMMM??l ckW??MMMMMd     k?W     k?W   dNM?MM?MXl  K?X      c??lcWMMMMMM??Xc     ")
    print("   ldldxxxkKkkkxkkxxxxxxdddxXkdxKXKkkxxxkKkkkxkKkxddddd     cl          cl            cldlc     clllllll          cllllllc     cllllll       lc      lc      ldll      l        cc  clllllllc       ")
    print("  cdddddxxxxxxkkkxxxddxxxxxkKXkdKXXKKkkkkKKKkddkdllllldlcclc                                                                                                                                        ")
    print("  cdxxxkkkkkkkkkkxxddddddxxxxxxdxxxxxddddllcccccccccccccccdddc                                                                                                                                      ")
    print("  cdxxxkxkkkkkxdllcccccccccccccccccccclllcccccccccccccccccclllc                                                                                                                                     ")
    print("  cdxxkkkkxdlccccccccccccccccccccccccxKKKkdccc  cccccccccccccld                                                                                                                                     ")
    print("  cdxxxxlccccccccccccccccccccccccccclkkkkxxdcccccccccclcccccclxc                 cxxxxxxxd     lxxxxxxxl  cdxxxxxxl    cxxxxxxxxl   lxxxxxxdc  cxxxxxxxl   cdxxxxxxxxxdc cdxxxxxxxl                 ")
    print("  cddddl  ccccccccccccccccccccccccccdxxxxxxxdcccc ccccccccccccl                  X?MNNNNW?MK cW?WNNNNNNk kM?NNNNNW?Nc K?MNNNNNNNx lW?WNNNNW?Mx k?MNNNNW?MXcdNNNNM?MNNNNlk?MNNNNNNNk                 ")
    print("  cllddddllccccccccccccclllddddlllldxxdldddddddlccccccccccccldl                  X?X     cM?xk?W         M?k     lM?   ??xcccc     K?W      N?N k?W    cK?Mc    N?X     M?Kcccc                     ")
    print("   cldddldxxdccccccclldddxNWXkddldkKkdllldxxdxKkxxxxkkkkkkkxxxd                  X?NddddxK?Mlk?W         M????????Mk  xW??????MXc K?????????Nl k?W       M?x    N?X     dN??????MXl                 ")
    print("   cldlddxddlllllllldddxkkKKkxxkkKKXXXXkdddxXWNXKKKKKXXXXKKkkkx                  X?MWWWWWNkc k?W         M?kcccccc      ccccclW?X K?Wcccccc    k?W       M?x    N?X        cccccX?N                 ")
    print("clddddxxxxxxkkKKXXNNNNNNNNNXXXKKKKKXNNWWXxdkNWWNXXXXXNNXXXKkkkxl                 X?X         k?W         k?MNNNNNNNXlcKXXXXXXN?Md lM?WNNNNNNNk k?W       M?x    N?X     KXXXXXXNM?x                 ")
    print("dddxxxkkkkkkKKKXXXNNNWNNNNNNNXXXXXNNNNNXkxdkXNNXXXXXXNXXKKkkkkxd                 lkl         cxd          cxkkkkkkkxc xkkkkkkkdc    dkkkkkkkkd cxd       dxc    lkl     dkkkkkkkxc                  ")
    print("xxxxxkkkkkKKXXXNNNNNNNNWNNNNNNNXXXXXXXXKKKKKKKKXXXXXNNXXXKKKKkxc                                                                                                                                    ")
    print("xxkkkxkkkkkkKKXNNNNNNNNNNNWWWWWNNXXXNNXXXXNNNNXXNNNXXNXKXXKKkxl                                                                                                                                     ")
    print("xxxxkkkkxxxkkkKXXNNNNNNNNNNNWWWWNNWNNNNNNNNNNNNNXXXNWWXKKkxdlc                                                                                                                                      ")
    print("dxxxxkkkkkkkKkkkkKKXXXXXNNNNNNWWNNXXNNNNNNNXXKkkkkkkXWMWXdc                                                                                                                                         ")
    print("ldxxxkkkkkkkkkkkkkxxxxxxkkkKXXXKkxxxxkkkkkkxxdddxdxxddkNWWkc cllc                                                                                                                                   ")
    print(" cldxddldddddxxddddllldxkkxkkxxxdddddllllldlldlddlddddddxXNNKddddddcclllcc                                                                                                                          ")
    print("    ccllllllddddddddxxxddkkxxxxdxxxdddddddddddlddlllllllllxkxlldddddddxddddllc                                                                                                                      ")
    print("    ccllllllllddddxxxdxxxxxxxxxddxxddddddddddllllllllllllldllllddddddddlddddddlc                                                                                                                    ")
    print("     llllllllddddxxddxdddxkKkxxddddddddddddddddddddxddddddldllddddddlddlddddddddc                                                                                                                   ")
    print("     llllllddlddxxdllddddddxxxxdddxxdxxddxxxxxdddxdxxdxxxdxdddldddddldlldddddddddlc                                                                                                                 ")
    print("     llldldddldkdllldddxddxxxxxdddxxxdddxdddddddddddddxxxxxddxdddxxdddldddddddddddc                                                                                                                 ")
    print("     llldddddxxdllddxxxdxxxxxxddddxxxxdxxdxxxxxxxddxdddxddddxxddxxxdddddddddddddddc                                                                                                                 ")
    print("     cldddddxdlldxxddxxddddddxxdxxxddxxxxxxxxxxxxxxxxddddxddxdddxddxddddddddddddddc                                                                                                                 ")
    print("     cclllllldxxdddxdddddddddxkxxxddxxxxdxxxxxxxxddxxxxddxdxxxxxxdxdddldddddddddxdc                                                                                                                 ")
    print("    clllllldxxdxxxxddddddxxxxdxkddddxxxxxxxxxxxxxddxxxxxxdddxxxxxdxdddddddddddddxdc                                                                                                                 ")
    print("   clllllldxdxxxddddddddddxxxxxxxddddddddxxxxxxxxxddxxxxdxdddxxddxddxdddddddddddxdl                                                                                                                 ")
    print("  llllllllldddddxddddddllldxxxxdxxdldllddxxxxxxdxddddddddxdddddddxddddddddddddddxdc                                                                                                                 ")
    print("  ccccccccccccccccccccccccccccccccccc ccccccccccccc                                                                                                                                                 ")
    sleep(3)
    print("                                                                                                                                                                      ")
    print("                                  cdkkkkkkkkkx  lkkc        ckkc   cdkkkkkkkkkd lxl         lxl dkl   dxc         ddc  lxkkkkkkkxl                                    ")
    print("                                cKM??MMMMMMMMWl X??x        k??k  xM??MMMMMMMMX W?M       lX??Xc??W  d??X       xW??kcX???MMMMMM??Wl                                  ")
    print("                                k??Xc           X??x        K??k l??Ml          M?M     lX??Wx c??W  d??X     xW??Xl k??Xc      x??W                                  ")
    print("                                lM?MKKKKKKkxc   X??x        K??k l??W           M?M   dN??Wx   c??W  d??X  ckW??Xl   K??NKKKKKKKW??K                                  ")
    print("                                 lkNWWWWWWM??K  K??k        K??k l??W           M?McdN??Wx     c??W  d??XckW??Xl     K??MMMMMMMMWXd                                   ")
    print("                                          cN??d lM?Md       K??k l??W           M?MN??Nd       c??W  d??WM?MKl       K??k                                             ")
    print("                                ckkKKKKKKKXM?Wc  lN??WXKKKKKN??k l??W           M???Nd         c??W  d???MKl         dM?MXKKKKKKKKKd                                  ")
    print("                                dWWWWWWWWWWNkc     lkXWWWWWWWWWd cNWk           XMNd           cXWK  lWWKl            lKNWWWWWWWWWWK                                  ")
    print("                                                                                                                                                                      ")
    print("                               ckXx  xNNc             cdKXNNNNNNNk  kNNNNNNNNNNXxc cKNNNNNNNNNNNNNK  dKNNNNNNNNNK xNNNNNNNNNNXkc  dXNNNNNNNNNNNNd                     ")
    print("                             cKM??M  X??d            kM??WNXXXXXXd  xXXXXXXXXXN??Wl kXXXXX??MXXXXXk X??WXXXXXXXXk dXXXXXXXXXNM?Md lXXXXXXXXW???Wd                     ")
    print("                           cKM?M??M  X??d           X??Xl                      K??k      c??W      l??W                      x??X        lX??Wx                       ")
    print("                         cKM?MkcM?M  X??d          d??N              lKNWWWWWWWM??k      c??W      l??W            lKNWWWWWWWM??X      cKM?Mk                         ")
    print("                       cKM?Mkc  M?M  X??d          l??Wc            k??WXXXXXXXW??k      c??W      l??W           x??MXXXXXXXN??X    cKM?Mkc                          ")
    print("                     lXM?Mkc    M?M  X??x           K??Wxc          W??d       X??k      c??W      l??W           N??x       k??X  ckM?MKc                            ")
    print("                    K??Mkc      M?M  lW??WWWWWWWWNl  dN???MWWWWWWk  xM??WWWWWWM??Nc      c??W      l??W           dW??WWWWWWM??Wl dW???MWWWWWWWWx                     ")
    print("                    xKxc        kXk    dkKKKKKKKKKc    cxkKKKKKKKd   cxKKKKKKKKkl         xKx       kKd             dKKKKKKKKkd   lKKKKKKKKKKKKKl                     ")
    print("                                                                                                                                                                      ")
    print("                                                                                                         xWWc                                                         ")
    print("                                                                                                         cK?X                                                         ")
    print("                                                                                                          l?d                                                         ")
    print("                                                                                                         kM?k                                                         ")
    print("                                                                                                         K??d                                                         ")
    print("                                                                                                         K??d                                                         ")
    print("                                                                                                         k??x                                                         ")
    print("                                                                                                         k??k                                                         ")
    print("                                                                                                         x??K                                                         ")
    print("                                          lKXxc        ldkKNWMWNXKxdlc lxXkl   ldkKXKKkxxdllc            x??X                                                         ")
    print("                                        cdxcx?Mkc  kNWWNKkxddMWlX?NW?MM??kxXWWM??MM??WM??????MMWWNXXKkxxcx??N                                                         ")
    print("                                        c cccK??Wx dxxkKXNM?M??MM?NN?kN??d l??kc  x??ck?McX?WdK??XN??NW?xd??MNXKkkl                                                   ")
    print("                                         XM?????KllWNXKKXdkkcMWlX?NN?WM??WNN??NXNWM??MM??NM?MKN??KK?MlK?ll???xWNkMk                                                   ")
    print("                                          cclX??x   cWxxMcKkl?MlK?xk?lK??xKk??NkXck?MlK?MdN?WkX??XN?MNMMcl???WMMW?k                                                   ")
    print("                                          KNXWWXl   cxc c   l?????MM?NW??xNk??NxX x?MkX?MxN?NdK??xK?WlKW l???xNKcMk                                                   ")
    print("                                          lWXKMkc   cKdlNckNd?MdX?KX?kX??xxd??Mlx x?MNW??WM?MM??MNNNNNNNdxWWNkxxdkxdc                                                 ")
    print("                                          xWKXXMl   cXdcKcldx?MkN?XX?kX??KWx???kN x?W k?McX?KK?Xl     dW????????????MXd                                               ")
    print("                                          XXdc xK         ccxNNXNWNXXKKNNl cKXNl  x??MM??M?????WxkNNWW??????????????Nxxc                                              ")
    print("                                        lxMKKXNNMNNNNWNNNNNXXXXKKKKKKKKKKKKkkkxxdllxKXXNWMM??MNXddXXXXXXXXXXWM??????Wkdc                                              ")
    print("                                    lkNM???MWWNNNXXXNXkxl                         cc       cc             lkXN?????????Mx                                             ")
    print("                                 ckW??WXkdl                         dKKKKKKXXKxdc                             cKW????????dkKKkl                                       ")
    print("                                xMMKxc                     cXMMXccxW???WNKkdc                      c             N?????????????Xl                                     ")
    print("                                N?Nc    cc       cdxkxdc  dW????MM?MXdc          lxXNWWWNNKkdcdKNWM?MWXkl   dxxdllN?????????????MKNMWx                                ")
    print("                              lNNkl   cK??MXx cxN??????MXkM??????MKl      lddcckW????????????????????????NxNWNXXXNWMMMMM??????????????k                               ")
    print("                             cdc    cdX??????MM????????????????Mkc  dkkxkM????M?????????????MWNXKkxdlllllllc            cdkW??????????W                               ")
    print("                               cdkXWMWKkkkkkkkkkkkkkkkkkkxxdllc    xXNWM???????????????????MWNNXXKKkkxxddllcc              cK?????????N                               ")
    print("                           cdKW??WKxc    ccc                            cldkXNM??????????????????????????????MWNXkxdc cldkkkxX????????Nc                              ")
    print("                          k?MNKdc   lxKXW????MMMWWNNNXXXKKkkkkxxxxxxxxxxxxxxkkkKXWM??????????????????????????????????M?????????????????Wx                             ")
    print("                         cxd  clxKNM??????????????????????MMMMMMMMWWWWWNNNNNNNXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKc                            ")
    print("                            cdxxxxxxxxddddddllllllccccllllldddxxxxkkKKKKXXXXNNNNNWWWWWWMMMMMMMMMMMMMMMMWWWWWWWWWNNNNNXXXXXKKKKkkkxxxdddc                              ")
    print("                                     cxkkkKXXXNNWWWMM?????????????????????????????????????????????????????????????????????????????????X                               ")
    print("                                     kXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNNNNNNNNNNNNNNNWWWWMMMMMM??????????????X                                ")
    print("                                                                                   ccllddxxkkKKXXXNNNWWWMMMM???????????????????????MX                                 ")                                                               
    playsound.playsound('Sounds/Narrator/survive.wav', True)
    input("Press enter to continue...")
    print("")
